# Generated by Django 4.0.3 on 2022-03-31 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hardware', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('processor', models.CharField(max_length=250)),
                ('display', models.CharField(max_length=500)),
                ('ram', models.CharField(max_length=100)),
                ('storage', models.CharField(max_length=100)),
                ('os', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('image', models.CharField(blank=True, default=None, max_length=2000, null=True)),
                ('customizations', models.ManyToManyField(to='main_app.customize')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('review', models.CharField(choices=[('E', 'Excellent'), ('G', 'Good'), ('A', 'Average'), ('S', 'Subpar'), ('B', 'Bad')], default='G', max_length=1)),
                ('tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.tech')),
            ],
            options={
                'ordering': ['date', 'review'],
            },
        ),
    ]
