# Generated by Django 4.0.3 on 2022-03-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('processor', models.CharField(max_length=250)),
                ('display', models.CharField(max_length=500)),
                ('ram', models.CharField(max_length=100)),
                ('storage', models.CharField(max_length=100)),
                ('os', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('image', models.CharField(blank=True, default=None, max_length=2000, null=True)),
            ],
        ),
    ]
