# Generated by Django 4.0.3 on 2022-03-30 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('review', models.CharField(choices=[('E', 'Excellent'), ('G', 'Good'), ('A', 'Average'), ('S', 'Subpar'), ('B', 'Bad')], default='G', max_length=1)),
                ('tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.tech')),
            ],
            options={
                'ordering': ['date', 'review'],
            },
        ),
    ]
